name: build-test
run-name: Test and Build
on:
  push:
    branches-ignore:
      - master
jobs:
  biome-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".tool-versions"
      - run: npm install
      - run: npm run lint
  build:
    runs-on: ubuntu-latest
    env:
      PUBLIC_URL: zachhuxford.io
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".tool-versions"
      - run: npm install
      - run: npm run build:tokens
      - run: npm run build
      - uses: actions/upload-pages-artifact@master
        with:
          path: build
